### ISSUE TITLE
Add support for mouse

### ISSUE THREAD

**Issue by hh** [lvht/btk#3]
It looks like it should be pretty straight forward.
I'll start documenting what I find here and welcome discussion.

**Comment by lvht** [comment]
basic mouse support has been added at d8692026353ebdeb1ff82644f2f42180b148b9c5, d8692026353ebdeb1ff82644f2f42180b148b9c5

works:
- movement
- left button, right button, wheel button

not works:
- wheel scroll

**Comment by hh** [comment]
This looks great! I hope to take a closer look soon.

It may be my python version, but the call to super is failing on my machine.

```
# python --version
Python 2.7.3
```

```
# python btk.py
Traceback (most recent call last):
  File "btk.py", line 26, in <module>
    mouse = Mouse(mouse_dev_paths + keyboard_dev_paths)
  File "/home/root/btk/inputdev.py", line 26, in __init__
    super().__init__(dev_path, report_id)
TypeError: super() takes at least 1 argument (0 given)
```
