### ISSUE TITLE
Program Entered Main Loop But Did Nothing

### ISSUE THREAD

**Issue by ericwan78** [lvht/btk#8]
I tested the program with all dependencies installed. And I verified that the program entered the gobject main loop. But I couldn't see the bt device from another computer. Any suggestion?

**Comment by ai0** [comment]
try python ./agent.py to pair device first?

**Comment by lvht** [comment]
@ai0 agent.py has not been mantained for a while. Please use system util like bluetoothctl to pair device

**Comment by lvht** [comment]
Please update code from master branch, and try again.
