### ISSUE TITLE
mouse button do not work

### ISSUE THREAD

**Issue by lvht** [lvht/btk#9]

**Comment by hh** [comment]
Looking

**Comment by hh** [comment]
Check out #11

**Comment by hh** [comment]
Still need scroll buttons, but I'm not sure how to send them :)

**Comment by lvht** [comment]
@hh :+1:

**Comment by hh** [comment]
Yeah! I'm happily using a Beagle Bone Black embedded in my keyboard (and using a wireless logitech mouse) with my laptop over bluetooth now.
